// @generated by scripts/generate-docs-static-data.vite.ts — do not edit
import type { SerializedPageTree } from 'fumadocs-core/source/client';

export const pageTree = {
  "$fumadocs_loader": "page-tree",
  "data": {
    "type": "root",
    "$ref": {
      "folder": "",
      "meta": "meta.json"
    },
    "$id": "root",
    "name": "OpenNOW",
    "children": [
      {
        "$id": "index.mdx",
        "type": "page",
        "name": "OpenNOW",
        "description": "Product, setup, architecture, and troubleshooting docs for the open-source OpenNOW clients",
        "icon": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-monitor-play\" aria-hidden=\"true\"><path d=\"M15.033 9.44a.647.647 0 0 1 0 1.12l-4.065 2.352a.645.645 0 0 1-.968-.56V7.648a.645.645 0 0 1 .967-.56z\"></path><path d=\"M12 17v4\"></path><path d=\"M8 21h8\"></path><rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\"></rect></svg>",
        "url": "/docs",
        "$ref": "index.mdx"
      },
      {
        "type": "folder",
        "name": "Guides",
        "defaultOpen": true,
        "children": [
          {
            "$id": "guides/getting-started.mdx",
            "type": "page",
            "name": "Getting Started",
            "description": "Download, install, first launch, and source builds for OpenNOW",
            "url": "/docs/guides/getting-started",
            "$ref": "guides/getting-started.mdx"
          },
          {
            "$id": "guides/troubleshooting.mdx",
            "type": "page",
            "name": "Troubleshooting",
            "description": "Diagnose sign-in, launch, stream quality, video, audio, input, and native-streamer problems",
            "icon": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-wrench\" aria-hidden=\"true\"><path d=\"M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z\"></path></svg>",
            "url": "/docs/guides/troubleshooting",
            "$ref": "guides/troubleshooting.mdx"
          },
          {
            "$id": "guides/nintendo-switch.mdx",
            "type": "page",
            "name": "Nintendo Switch",
            "description": "Install, configure, and use the native OpenNOW-Switch homebrew client",
            "icon": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-gamepad2 lucide-gamepad-2\" aria-hidden=\"true\"><line x1=\"6\" x2=\"10\" y1=\"11\" y2=\"11\"></line><line x1=\"8\" x2=\"8\" y1=\"9\" y2=\"13\"></line><line x1=\"15\" x2=\"15.01\" y1=\"12\" y2=\"12\"></line><line x1=\"18\" x2=\"18.01\" y1=\"10\" y2=\"10\"></line><path d=\"M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z\"></path></svg>",
            "url": "/docs/guides/nintendo-switch",
            "$ref": "guides/nintendo-switch.mdx"
          }
        ],
        "$id": "guides",
        "$ref": {
          "folder": "guides",
          "meta": "guides/meta.json"
        },
        "icon": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-compass\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><path d=\"m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z\"></path></svg>"
      },
      {
        "$id": "development.mdx",
        "type": "page",
        "name": "Development Guide",
        "description": "Local setup, scripts, native streamer builds, CI, and release packaging",
        "url": "/docs/development",
        "$ref": "development.mdx"
      },
      {
        "type": "folder",
        "name": "Architecture",
        "defaultOpen": true,
        "children": [
          {
            "$id": "architecture/overview.md",
            "type": "page",
            "name": "Architecture Overview",
            "description": "How the OpenNOW Electron client, renderer WebRTC path, and native streamer fit together",
            "url": "/docs/architecture/overview",
            "$ref": "architecture/overview.md"
          }
        ],
        "$id": "architecture",
        "$ref": {
          "folder": "architecture",
          "meta": "architecture/meta.json"
        },
        "icon": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-network\" aria-hidden=\"true\"><rect x=\"16\" y=\"16\" width=\"6\" height=\"6\" rx=\"1\"></rect><rect x=\"2\" y=\"16\" width=\"6\" height=\"6\" rx=\"1\"></rect><rect x=\"9\" y=\"2\" width=\"6\" height=\"6\" rx=\"1\"></rect><path d=\"M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3\"></path><path d=\"M12 12V8\"></path></svg>"
      },
      {
        "type": "folder",
        "name": "Reference",
        "defaultOpen": true,
        "children": [
          {
            "$id": "reference/authentication.md",
            "type": "page",
            "name": "Authentication",
            "description": "OAuth + PKCE, QR device login, and token lifecycle in OpenNOW",
            "url": "/docs/reference/authentication",
            "$ref": "reference/authentication.md"
          },
          {
            "$id": "reference/webrtc.mdx",
            "type": "page",
            "name": "WebRTC",
            "description": "Signaling, SDP negotiation, NVST SDP, data channels, diagnostics, and Chromium acceleration in OpenNOW",
            "url": "/docs/reference/webrtc",
            "$ref": "reference/webrtc.mdx"
          },
          {
            "$id": "reference/native-streamer.mdx",
            "type": "page",
            "name": "Native Streamer",
            "description": "Settings, protocol, executable lookup, GStreamer dependencies, diagnostics, and fallback behavior",
            "url": "/docs/reference/native-streamer",
            "$ref": "reference/native-streamer.mdx"
          },
          {
            "$id": "reference/media.mdx",
            "type": "page",
            "name": "Media",
            "description": "Screenshots, recordings, and local media storage in OpenNOW",
            "url": "/docs/reference/media",
            "$ref": "reference/media.mdx"
          },
          {
            "$id": "reference/input.mdx",
            "type": "page",
            "name": "Input",
            "description": "Keyboard, mouse, gamepad, clipboard, microphone, shortcuts, and native input behavior in OpenNOW",
            "url": "/docs/reference/input",
            "$ref": "reference/input.mdx"
          },
          {
            "$id": "reference/configuration.mdx",
            "type": "page",
            "name": "Configuration",
            "description": "Settings model, defaults, compatibility normalization, and storage for OpenNOW",
            "url": "/docs/reference/configuration",
            "$ref": "reference/configuration.mdx"
          }
        ],
        "$id": "reference",
        "$ref": {
          "folder": "reference",
          "meta": "reference/meta.json"
        },
        "icon": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-book-marked\" aria-hidden=\"true\"><path d=\"M10 2v8l3-3 3 3V2\"></path><path d=\"M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20\"></path></svg>"
      },
      {
        "type": "folder",
        "name": "Advanced",
        "defaultOpen": true,
        "children": [
          {
            "$id": "advanced/streamer-investigation.mdx",
            "type": "page",
            "name": "Native Streamer Architecture",
            "description": "Advanced notes on the Rust/GStreamer native streamer path",
            "url": "/docs/advanced/streamer-investigation",
            "$ref": "advanced/streamer-investigation.mdx"
          }
        ],
        "$id": "advanced",
        "$ref": {
          "folder": "advanced",
          "meta": "advanced/meta.json"
        },
        "icon": "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-flask-conical\" aria-hidden=\"true\"><path d=\"M14 2v6a2 2 0 0 0 .245.96l5.51 10.08A2 2 0 0 1 18 22H6a2 2 0 0 1-1.755-2.96l5.51-10.08A2 2 0 0 0 10 8V2\"></path><path d=\"M6.453 15h11.094\"></path><path d=\"M8.5 2h7\"></path></svg>"
      }
    ]
  }
} as SerializedPageTree;

const pages = {
  "advanced/streamer-investigation": {
    "path": "advanced/streamer-investigation.mdx",
    "markdownUrl": "/docs/advanced/streamer-investigation.md"
  },
  "architecture/overview": {
    "path": "architecture/overview.md",
    "markdownUrl": "/docs/architecture/overview.md"
  },
  "development": {
    "path": "development.mdx",
    "markdownUrl": "/docs/development.md"
  },
  "guides/getting-started": {
    "path": "guides/getting-started.mdx",
    "markdownUrl": "/docs/guides/getting-started.md"
  },
  "guides/nintendo-switch": {
    "path": "guides/nintendo-switch.mdx",
    "markdownUrl": "/docs/guides/nintendo-switch.md"
  },
  "guides/troubleshooting": {
    "path": "guides/troubleshooting.mdx",
    "markdownUrl": "/docs/guides/troubleshooting.md"
  },
  "": {
    "path": "index.mdx",
    "markdownUrl": "/docs/index.md"
  },
  "reference/authentication": {
    "path": "reference/authentication.md",
    "markdownUrl": "/docs/reference/authentication.md"
  },
  "reference/configuration": {
    "path": "reference/configuration.mdx",
    "markdownUrl": "/docs/reference/configuration.md"
  },
  "reference/input": {
    "path": "reference/input.mdx",
    "markdownUrl": "/docs/reference/input.md"
  },
  "reference/media": {
    "path": "reference/media.mdx",
    "markdownUrl": "/docs/reference/media.md"
  },
  "reference/native-streamer": {
    "path": "reference/native-streamer.mdx",
    "markdownUrl": "/docs/reference/native-streamer.md"
  },
  "reference/webrtc": {
    "path": "reference/webrtc.mdx",
    "markdownUrl": "/docs/reference/webrtc.md"
  }
} as Record<string, { path: string; markdownUrl: string }>;

export function getDocsPageData(slugs: string[]): { path: string; markdownUrl: string } | null {
  return pages[slugs.join('/')] ?? null;
}
