import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { source, slugsToMarkdownPath } from '../src/lib/source';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = path.join(rootDir, 'src/lib/docsStaticData.gen.ts');

const pageTree = await source.serializePageTree(source.getPageTree());
const pages: Record<string, { path: string; markdownUrl: string }> = {};

for (const page of source.getPages()) {
  pages[page.slugs.join('/')] = {
    path: page.path,
    markdownUrl: slugsToMarkdownPath(page.slugs).url,
  };
}

const content = `// @generated by scripts/generate-docs-static-data.vite.ts — do not edit
import type { SerializedPageTree } from 'fumadocs-core/source/client';

export const pageTree = ${JSON.stringify(pageTree, null, 2)} as SerializedPageTree;

const pages = ${JSON.stringify(pages, null, 2)} as Record<string, { path: string; markdownUrl: string }>;

export function getDocsPageData(slugs: string[]): { path: string; markdownUrl: string } | null {
  return pages[slugs.join('/')] ?? null;
}
`;

await writeFile(outputPath, content, 'utf-8');
